"""need to revert some changes again

Revision ID: 2fb1946ed681
Revises: e72b39c04611
Create Date: 2024-03-27 19:14:53.125664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fb1946ed681'
down_revision = 'e72b39c04611'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Messages')
    op.drop_table('Chat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Chat',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('chat_name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Messages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('message_body', sa.INTEGER(), nullable=True),
    sa.Column('message_user', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
