"""made some changes with the many to many relationships

Revision ID: 5e4bd7f25da9
Revises: d67e49d8bfb4
Create Date: 2024-03-19 16:54:31.435177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e4bd7f25da9'
down_revision = 'd67e49d8bfb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_posts', schema=None) as batch_op:
        batch_op.create_foreign_key("posts", 'posts', ['post_id'], ['id'])
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint("posts", type_='foreignkey')

    # ### end Alembic commands ###
