"""empty message

Revision ID: 7151eb88981a
Revises: 9b1425b4fbcf
Create Date: 2024-03-27 19:17:20.136440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7151eb88981a'
down_revision = '9b1425b4fbcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Messages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Messages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('message_body', sa.INTEGER(), nullable=True),
    sa.Column('message_user', sa.VARCHAR(), nullable=True),
    sa.Column('chat_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
