"""adding the chat and messages tables back

Revision ID: 9b1425b4fbcf
Revises: 2fb1946ed681
Create Date: 2024-03-27 19:15:45.413987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b1425b4fbcf'
down_revision = '2fb1946ed681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_name', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_body', sa.Integer(), nullable=True),
    sa.Column('message_user', sa.String(), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Messages')
    op.drop_table('chat')
    # ### end Alembic commands ###
