"""added a message database and a chat database with a user having many chats and chats having many messages

Revision ID: e72b39c04611
Revises: 5e4bd7f25da9
Create Date: 2024-03-27 18:52:51.018974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e72b39c04611'
down_revision = '5e4bd7f25da9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_body', sa.Integer(), nullable=True),
    sa.Column('message_user', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Messages')
    op.drop_table('Chat')
    # ### end Alembic commands ###
