"""profile adjustments

Revision ID: ec330285e66e
Revises: ac42feed32f4
Create Date: 2024-02-24 14:14:37.297558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec330285e66e'
down_revision = 'ac42feed32f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('followers', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('following', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('lift_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email')
        batch_op.drop_column('lift_type')
        batch_op.drop_column('bio')
        batch_op.drop_column('following')
        batch_op.drop_column('followers')

    # ### end Alembic commands ###
